from setuptools import find_packages, setup
setup(
name="ma cli",
    version="0.1",
    description="",
    author="Galen Curwen-McAdams",
    author_email='',
    platforms=["any"],
    license="Mozilla Public License 2.0 (MPL 2.0)",
    include_package_data=True,
    data_files = [("", ["LICENSE.txt","ma_cli/cameras.yaml"])],
    url="",
    packages=find_packages(),
    install_requires=["attrs",
                      "curtsies",
                      "cmd2",
                      "paho-mqtt",
                      "Pillow",
                      "python-consul",
                      "redis",
                      "ruamel.yaml",
                      "zerorpc",
                      "lxml",
                      "lings"
                     ],
    dependency_links=["https://github.com/galencm/machinic-lings/tarball/master#egg=lings-0.1"],
    entry_points = {'console_scripts': ['ma-cli = ma_cli.ma_cli:main',
                                        'ma-deck = ma_cli.ma_deck:main',
                                        'ma-dm = ma_cli.ma_dm:main',
                                        'ma-sink = ma_cli.ma_sink:main',
                                        'ma-dial = ma_cli.ma_dial:main',
                                        'ma-vis = ma_cli.ma_vis:main',
                                        'ma-throw = ma_cli.ma_throw:main',
                                        'ma-dump = ma_cli.ma_dump:main',
                                        'ma-load = ma_cli.ma_load:main'
                                        ],
                            },
)
